        spring.application.name=chroma
spring.datasource.url=jdbc:mysql://localhost:3306/chroma
spring.datasource.username=root
spring.datasource.password=yousefyahya1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
